#!/bin/sh

cat <<EOF

part-db version 0.1
Copyright (C) 2005 Christoph Lechner
http://www.cl-projects.de/

part-db version 0.2+
Copyright (C) 2009 K. Jacobs, ajfrenzel, tgrziwa, d.lipschinski, Michael Buesch, bubbles.red, Matthias Weißer, Urban B., André Althaus, Udo Neist (see also authors.php)
http://code.google.com/p/part-db/

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
"as" published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

EOF

# Passwort generator
PWGEN=`which pwgen`

# MySQL-user with rights to create a database
DB_ADMIN_USER=root
DB_ADMIN_PASS=

# Database
DB_HOST=localhost
DB_NAME=part-db
DB_USER_PARTDB=
if [ -x $PWGEN ]; then
	DB_PASS_PARTDB=`$PWGEN -c -s -1`
else
	DB_PASS_PARTDB=''
fi

# SQL-Script
SQL_INSTALL="readme/createtables-FOR-V0.2.1-rev12.sql"

case "$1" in
	-a)
		echo -e "You accepted the license!\n"
		break;;
	-h|--help)
		echo -e "$0 - installing part-db\n"
		echo -e "-a\t\taccept license"
		echo -e "-h|--help\tthis help\n"
		exit;;
	*)
		while true; do
			read -e -t 10 -i "n" -p "Do you wish to install this program? (y/n) " yn 
			case $yn in
				[Yy]* ) break;;
				[Nn]* ) exit;;
				* ) echo "Please answer yes or no.";;
			esac
		done
		echo
		;;
esac

# Installation of Database

echo -e "* Enter the data for the installation of the database.\n"
read -e -t 10 -i "$DB_HOST" -p "Hostname ($DB_HOST): " DB_HOST
read -e -t 10 -i "$DB_NAME" -p "Database ($DB_NAME): " DB_NAME
echo
read -e -t 10 -i "$DB_ADMIN_USER" -p "Admin user ($DB_ADMIN_USER): " DB_ADMIN_USER
read -e -t 10 -i "$DB_ADMIN_PASS" -p "Password: " DB_ADMIN_PASS
echo
read -e -t 10 -i "$DB_NAME" -p "User ($DB_NAME): " DB_USER_PARTDB
if [ -x $PWGEN ]; then
	read -e -t 10 -i "$DB_PASS_PARTDB" -p "Password (generated by pwgen): " DB_PASS_PARTDB
else
	read -e -t 10 -p "Password: " DB_PASS_PARTDB
fi

echo -ne "\ninstalling database, please wait..."
sed "s/DB_NAME/$DB_NAME/g;s/DB_HOST/$DB_HOST/g;s/DB_USER_PARTDB/$DB_USER_PARTDB/g;s/DB_PASS_PARTDB/$DB_PASS_PARTDB/g" <$SQL_INSTALL | mysql -u$DB_ADMIN_USER -p$DB_ADMIN_PASS -h$DB_HOST
echo " ok."

# Creating config_db.php

echo -ne "\ncreating config_db.php.new..."
sed "s/DB_NAME/$DB_NAME/g;s/DB_HOST/$DB_HOST/g;s/DB_USER_PARTDB/$DB_USER_PARTDB_PARTDB/g;s/DB_PASS_PARTDB/$DB_PASS_PARTDB_PARTDB/g" <config_db.php_template >config_db.php.new
echo -e " finished. Please rename this file to config_db.php.\n"

# chgrp/chmod backup/update-directory

if [[ $EUID -eq 0 ]]; then
	echo -ne "changing group of backup-directory..."
	APACHECONFDIR=$(dirname `apache2ctl -V | grep "SERVER_CONFIG_FILE" | cut -d= -f 2 | sed 's/"//g'`)
	chgrp `grep -i "^Group " $APACHECONFDIR/* | cut -d" " -f 2` backup
	chmod 775 backup
	chgrp `grep -i "^Group " $APACHECONFDIR/* | cut -d" " -f 2` update
	chmod 775 update
	echo -e " done.\n"
fi
