<?php

/**
 * Created by PhpStorm.
 * User: janhb
 * Date: 01.01.2017
 * Time: 15:58
 */
class LibTest extends PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        include_once "lib/lib.php";
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testOddDetect()
    {
        $this->assertTrue(is_odd(3));
    }

    public function testEvenDetect()
    {
        $this->assertFalse(is_odd(4));
    }

    public function test_toUnixPath()
    {
        $this->assertEquals(to_unix_path("\\test\\test.jpg"),"/test/test.jpg");
    }




}
