<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 13 Feb 2013 01:33:17 +0000
 */
$conf['title'] = 'Part-DB Dokumentation';
$conf['lang'] = 'de';
$conf['license'] = '';
$conf['useacl'] = 0;
$conf['superuser'] = '@admin';
$conf['cachetime'] = -1;
$conf['updatecheck'] = 0;
$conf['locktime'] = 0;
